
import './ChatGptBadge.scss'

import ChatGPTLogo from './../resources/ChatGPT_logo.svg'

export default function ChatGptBadge() {
    return <div
        className="chatgpt-badge"
        onClick={function() {
            window.location.href="https://chat.openai.com/"
        }}
    >
        <section className="wrapper">
            <img src={ChatGPTLogo} alt="" />
            <div>
                <span>Contains Text Generated By</span>
                <span>ChatGPT</span>
            </div>
        </section>
    </div>
}